change test UI, added file myConf.properties with login and pass. add…
YuliaTen/YandexTestSelenid pull request #1
Opened 2022-04-20 20:07 UTC by YuliaTen

… allure properties

2022-04-21 20:56 UTC, dKusakin requested changes
- `try-with-resources`
- разобраться со `staic`'ами
- селекторы сделать поаккуратнее
- проверить `mvn test` и, в случае краха, исправить
- пересмотреть шаги и что-то собрать в шаги побольше
- постараться хранить в `src/test` *только* сами тесты, а всякий подручный функционал перевезти в `src/main`. Это обеспечивает независимость. Тебе всё это растаскивать на модули придется в любом случае, так что подготовься к этому

2022-04-21 20:56 UTC, dKusakin commented on pom.xml
>              <version>5.8.2</version>
Если используешь одну версию артефакта несколько раз, то лучше определить под неё макрос и юзать его. Потом меньше головной боли будет при обновлении

2022-04-21 20:56 UTC, dKusakin commented on pom.xml
> +            <version>2.17.3</version>
И у аллюра

2022-04-21 20:56 UTC, dKusakin commented on pom.xml
> +                    <reportVersion>2.17.2</reportVersion>
Опа, а тут уже другая версия

2022-04-21 20:56 UTC, dKusakin commented on pom.xml
> +                         <version>1.9.9.1</version>
И версия этого у тебя выше тоже упоминается

2022-04-21 20:56 UTC, dKusakin commented on pom.xml
> +                        <artifactId>junit-platform-surefire-provider</artifactId>
Вот этого парня лучше убрать. Его даже уже рекомендуют не указывать

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/dataSource/ConfProperties.java
> +        return PROPERTIES.getProperty(key); } }
Перенеси нормально скобки. Крайне болезненно такая запись выглядит

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/dataSource/ConfProperties.java
> +            fileInputStream = new FileInputStream("src/test/resources/myConf.properties");
Во-первых, есть метод у класса `getResourceAsStream(String)`. Его использование более предпочтительно, он будет искать ресурс в classpath и имя там указывается уже вместо `"src/main/resources/subfolder/resourceName"` просто `"subfolder/resourceName"`
Во-вторых, `try-with-resources` ?

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/dataSource/ConfProperties.java
> +                    e.printStackTrace(); } } }
Ох и не в ладах ты со скобками) Автоформат тут тоже в помощь

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/dataSource/ConfProperties.java
> +    protected static FileInputStream fileInputStream;
А нужна тебе эта переменная тут?
Ты её только для считывания `Properties` используешь, а потом ни разу в её сторону не смотришь

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/dataSource/TestData.java
>      private static String content = "тестовое  тело письма";
Я смотрю ты часто юзаешь статики. Сейчас ты прибиваешь всё гвоздями.
А что если мы захотим в разных тестах заиспользовать разные тестовые данные в разных тестах?
А если какой-нибудь тест это поменяет, а в следующем ты не ожидала этих изменений (тесты запустились в другом порядке)?
Этим ты плодишь глобальные состояния своих тестов, чем заставляешь дополнительно следить за ним и делаешь тесты зависимыми друг от друга, а это противоречит идеологии атомарности.
Советую пересмотреть своё отношение к статике и почитать статейки на темы "вред static в java", "static - Не ООП" и т.д.

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/pages/MailPage.java
>          return  $$(byXpath("//span[@class='mail-MessageSnippet-Item mail-MessageSnippet-Item_subject']"));
Смотрю и не вижу разницы с предыдущим. Зачем одинаковые?

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/pages/MailPage.java
>          return  $$(byXpath("//span[@class='mail-MessageSnippet-Item mail-MessageSnippet-Item_subject']"));
На самом деле селектор смахивает на генеренный. Можно же попробовать по частичному соответствию подобрать., а так поменяют один класс и придется актуализировать

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/pages/MailPage.java
>          return $(byXpath("//div[@class='cke_wysiwyg_div cke_reset cke_enable_context_menu cke_editable cke_editable_themed " +
Вот этот прям совсем будто генерили, да ещё и классы не человекопонятные. Есть высокая вероятность, что такое долго не проживет. Да и разбирать это не очень легко.
Дальше такие же селекторы кривоватые, к каждому не буду писать, я думаю, что ты мою мысль поймёшь

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/pages/MailPage.java
>      public static SelenideElement income() {
А тут какой пруф от статика? На кой нам постоянно эти методы в памяти хранить

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/pages/MailPage.java
> +    @Step("Получение элемента для ввода логина")
Степами необязательно прям всё помечать. Обычно достаточно именно действия, т.е. "Ввести логин", "Открыть форму". А просто "Получить кнопку", "Получить поле" особо толка не имеет. Так-то у селенида есть доп к аллюру, который логирует селекторы

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/uiTest/YandexMail.java
>          addListener(new Highlighter());
`Deprecated`-метод используешь. Да и `Highlighter` наследуется от `Deprecated`-класса. Надо бы поправить на актуальный

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/uiTest/YandexMail.java
>  public class YandexMail extends MailPage {
Так команда `mvn test` запускает эти тесты? Сколько запущенных пишет в выводе?

2022-04-21 20:56 UTC, dKusakin commented on pom.xml
> +            <artifactId>allure-junit5</artifactId>
`allure-selenide` тоже можно добавить в копилку

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/uiTest/YandexMail.java
> +        TestData.waiting(3000);
У селенида есть свой `Selenide.sleep(millis)`, а вообще ждать надо чего-то определенного, а не просто так

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/uiTest/YandexMail.java
> +        TestData.waiting(3000);
Тот же вопрос. Зачем?

2022-04-21 20:56 UTC, dKusakin commented on src/test/java/uiTest/YandexMail.java
>          writeMail().click();
Вот тут, например, можно было б собрать в более общие шаги и, возможно, засунуть их в `PageObject`:
- отправить письмо
- перейти в отправленные
- проверить присутствие только что отправляемого письма

Это повысит читаемость как кода, так и отчёта. С остальными, думаю, сама сможешь подобное провернуть.

2022-05-05 13:26 UTC, dKusakin requested changes

2022-05-05 13:26 UTC, dKusakin commented on pom.xml
> +        <allure-junit5.version>2.17.3</allure-junit5.version>
Зачем 2 разных переменных для одной и той же версии?
У тебя же они одинаковые, т.к. в них используется одинаковая версия ядра allure.
Так что сделай одну и пользуй во всех местах, а то есть риск при смене одной выхватить конфликт в другой

2022-05-05 13:26 UTC, dKusakin commented on pom.xml
> +        <junit-jupiter-api.version>5.8.2</junit-jupiter-api.version>
Та же ситуация, что и выше с allure

2022-05-05 13:26 UTC, dKusakin commented on pom.xml
> +            <artifactId>allure-junit5</artifactId>
Up
Добавить бы, тогда селекторы в отчёте тоже будут

2022-05-05 13:26 UTC, dKusakin commented on src/main/java/Utils/Base64.java
> +package Utils;
Название пакета должно начинаться со *строчной* буквы

2022-05-05 13:26 UTC, dKusakin commented on src/main/java/Utils/ConfProperties.java
> +            fileInputStream = new FileInputStream("src/main/resources/myConf.properties");
Уже писал, но force push похерил коммент, так что ещё раз:
Во-первых, есть метод у класса `getResourceAsStream(String)`. Его использование более предпочтительно, он будет искать ресурс в classpath и имя там указывается уже вместо `"src/main/resources/subfolder/resourceName"` просто `"subfolder/resourceName"`
Во-вторых, `try-with-resources` ?

2022-05-05 13:26 UTC, dKusakin commented on src/main/java/Utils/ConfProperties.java
> +                    e.printStackTrace(); } } }
Про скобки тоже

2022-05-05 13:26 UTC, dKusakin commented on src/test/java/Utils/DBConnect.java
> +public class DBConnect {
Комменты классам, полям и методам

2022-05-05 13:26 UTC, dKusakin commented on src/test/java/Utils/DBConnect.java
> +        String connectionString = "jdbc:mysql://" + ConfProperties.getProperty("DBHOST") + ":"
Мб `String.format()` заиспользовать вместо конкатенации?

2022-05-05 13:26 UTC, dKusakin commented on src/test/java/Utils/DBConnect.java
> +        Class.forName("com.mysql.jdbc.Driver");
А эта штука для чего?

2022-05-05 13:26 UTC, dKusakin commented on src/test/java/Utils/Letters.java
> +    String subject;
Доступ точно по умолчанию?
Ну и комменты конечно

2022-05-05 13:26 UTC, dKusakin commented on src/test/java/Utils/TestData.java
> +    private  static DBConnect dbConnect = new DBConnect();
Как у тебя всё пляшет.
Пользуйся автоформатом (`Ctrl + Alt + L`) и всё будет ровненько

2022-05-10 15:00 UTC, YuliaTen commented on src/test/java/Utils/DBConnect.java
> +        Class.forName("com.mysql.jdbc.Driver");
нашла этот пример как подключение к бд, на твой вопрос инфу нашла тут  https://russianblogs.com/article/9324971904/, так понимаю что это инициализация экземпляра класса

2022-05-10 15:08 UTC, YuliaTen commented on src/test/java/Utils/TestData.java
> +    private  static DBConnect dbConnect = new DBConnect();
+

2022-05-10 19:50 UTC, YuliaTen commented on pom.xml
> +        <allure-junit5.version>2.17.3</allure-junit5.version>
надеюсь я правильно поправила

2022-05-10 19:52 UTC, YuliaTen commented on pom.xml
> +            <artifactId>allure-junit5</artifactId>
я пробовала, но результат мне не понравился , аллюр селенид специально не стала добавлять

2022-05-12 18:08 UTC, dKusakin commented on pom.xml
> +        <allure-junit5.version>2.17.3</allure-junit5.version>
Вполне, хоть и логичнее было её название не связывать с junit, а назвать просто `allureVersion` :)
Но это не страшно

2022-05-12 18:11 UTC, dKusakin commented on src/main/java/utils/Base64.java
> +public final class Base64 {
Назвать бы его чуть по-другому, а то сейчас как аналогичный класс в `java.util`

2022-05-12 18:27 UTC, dKusakin commented on src/test/java/pages/MailPage.java
> +        return $x("//*[contains(@class,'cke_editable_themed')]"); }
Пройдись по этому файлу автоформатом

2022-05-12 18:28 UTC, dKusakin commented on src/test/java/uiTest/YandexMailTest.java
> +}
И по этому тоже автоформатом

2022-05-12 19:30 UTC, dKusakin requested changes

2022-05-12 19:30 UTC, dKusakin commented on src/test/java/utils/TestData.java
> +public class TestData {
Что-то не очень понятна концепция этого класса. Смахивает на какой-то "God Object", который делает всё за всех.
Чем хуже будет хранить необходимые данные в самих тестах? Да, учетные данные и основную урлу ресурсов - не вопрос, они везде будут юзаться, но вот то же письмо или контент с адресатами уже вряд ли выйдут за рамки теста

2022-05-12 19:30 UTC, dKusakin commented on src/test/java/utils/TestData.java
> +    private Letters letter = dbConnect.getDataLetter();
А может в самом тестовом классе уже с БД работать? Зачем эта прослойка?

2022-05-12 19:30 UTC, dKusakin commented on src/test/java/utils/TestData.java
> +    private String myEmail = "yuliatestirova@yandex.ru";
Этот и следующие 2 параметра будут же к определённому тесту относиться. И да, имеют ли они смысл? Почему бы не дергать что-нибудь из БД? По идее, тесты не должны быть жестко завязаны на конкретные тестовые данные, хоть тут этого сильно и нет, но и смысла выделять отдельные тему и тело особо не вижу, а email свой из логина же можно взять

2022-05-12 19:30 UTC, dKusakin commented on src/main/java/utils/ConfProperties.java
> +import java.io.FileInputStream;
Ещё нужен?

2022-05-12 19:30 UTC, dKusakin commented on src/test/java/uiTest/YandexMailTest.java
> +        mailPage.checkContentMail(testData.getLetter().getContext());
Почему с объектом из `testData` сравниваешь, а не с локальным `letter`, который отправляли?

2022-05-12 19:30 UTC, dKusakin commented on src/test/java/uiTest/YandexMailTest.java
> +        mailPage.checkTopicMail(topicDate);
Я правильно понимаю, что этот метод проверяет самое верхнее письмо?
Где гарантия, что тебе ещё что-то не пришло и верхним не стало другое?

2022-05-12 19:30 UTC, dKusakin commented on src/test/java/pages/MailPage.java
> +    @Step("Проверка темы письма")
Всё же стоит указать, что ты еще и открываешь письмо

2022-05-12 19:30 UTC, dKusakin commented on src/test/java/uiTest/YandexMailTest.java
> +        mailPage.subjectMailTextVisible().filter(text(topicDate)).shouldBe(sizeGreaterThanOrEqual(1));
`sizeGreaterThan(0)` было б покороче :)

2022-05-12 19:30 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +        Letters letter = new Letters("start", "start", "start@yandex.ru");
По-моему, тут инициализация лишняя. Ты нигде этот объект не используешь. Можно объявление переменной в само тело цикла затащить

2022-05-12 19:30 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +    public ResultSet getLetter() {
А этот точно публичным должен быть?

2022-05-12 19:30 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +    Connection dbConnection;
Для чего это поле? Ты его сетишь и тут же кидаешь, но больше нигде не пользуешь

2022-05-12 19:30 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +        dbConnection = DriverManager.getConnection(connectionString,
Так, открытие соединения вижу, а закрывать где и когда будем? Ну и да, `getDbConnection()` каждый раз новое при вызове будет создавать?

2022-05-12 19:30 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +        Class.forName("com.mysql.cj.jdbc.Driver");
Без этой строки разве не пашет? Вроде писали, что явное указание уже не нужно

2022-05-12 19:30 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +                letter.setSubject(resultSet.getString(1));
Вот по номерам колонок как-то не очень стучаться. Сегодня так в запросе, завтра наоборот. Лучше по именам

2022-05-13 06:28 UTC, YuliaTen commented on src/main/java/utils/DBConnect.java
> +        Letters letter = new Letters("start", "start", "start@yandex.ru");
и внутри цикла её постоянно инициализировать и занимать память? мне кажется это неправильно

2022-05-13 06:28 UTC, YuliaTen commented on src/test/java/uiTest/YandexMailTest.java
> +        mailPage.checkTopicMail(topicDate);
этот метод проверяет по теме, фильтрует по ней, так что он ищет именно то что нужно

2022-05-13 07:58 UTC, YuliaTen commented on src/test/java/pages/MailPage.java
> +        return $x("//*[contains(@class,'cke_editable_themed')]"); }
поправила где более двух строк перенесла

2022-05-16 19:54 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +        PreparedStatement stat = null;
А нужен? Тоже сетишь, сразу используешь и забываешь, можно было б сразу `resSet` цепочкой просетить

2022-05-16 20:04 UTC, dKusakin commented on src/test/java/pages/MailPage.java
> +        subjectMailTextVisible().filter(text(topic)).first().shouldHave(text(topic)).click();
`shouldHave` тут в теории уже необязателен, ты ж фильтровала коллекцию как раз по тексту :)
Но ладно, видимо, есть причины)

2022-05-16 20:16 UTC, dKusakin requested changes

2022-05-16 20:16 UTC, dKusakin commented on src/test/java/uiTest/YandexMailTest.java
> +    public Letters getLetter() {
Зачем этот геттер? Поля ты точно только в этом тестовом классе будешь использовать

2022-05-16 20:16 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +            while (resultSet.next()) {
Логичнее здесь добавить ещё `resultSet != null`. Тогда можно будет избавиться от ~костыля~ сомнительного решения с перехватом `NPE`

2022-05-16 20:16 UTC, dKusakin commented on src/main/java/utils/DBConnect.java
> +        } finally {
Мб есть способ получше использования блока `finally`?

2022-05-18 08:00 UTC, YuliaTen commented on src/test/java/pages/MailPage.java
> +        subjectMailTextVisible().filter(text(topic)).first().shouldHave(text(topic)).click();
Да,я оставила так как номинально это идет как проверка вместо ассерта

2022-05-18 20:13 UTC, dKusakin commented on pom.xml
> +        <testOutputDirectory>target/allure-results</testOutputDirectory>
Не особо понимаю смысл этой настройки, тебе что-то дает хранение скомпилированных файлов тестов в директории с отчетом аллюра?

2022-05-18 20:16 UTC, dKusakin approved these changes
- отчет, конечно, странновато выглядит, шаги не очень систематизированы
- в помнике тоже есть шероховатости (использование deprecated-секций и ненужных настроек)
Однако, в целом, уже похоже на правду :)

2022-05-19 13:30 UTC, YuliaTen commented on pom.xml
> +        <testOutputDirectory>target/allure-results</testOutputDirectory>
нет, нашла это в общей инфе что так нужно. Приберу в следующем пр

2022-05-19 13:30 UTC, merged