create Api test, Pogo classes and auxiliary classes
YuliaTen/YandexTestSelenid pull request #2
Opened 2022-05-19 14:37 UTC by YuliaTen

create Api test, Pogo classes and auxiliary classes

2022-05-21 21:58 UTC, dKusakin commented on src/main/resources/myConf.properties
> +# ����� ���� ����������� ���������� �� ������ �����, ������ ���������, �� �������� ��������� �� ������
Странный текст. Чтобы враги не догадались?)
А по существу, похоже, что в какой-то момент кодировка уехала

2022-05-21 22:05 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +    @DisplayName("Авторизация и сохраниние необходимых данных, для уменьшения колличества запросов к сайту")
сохран**е**ние

2022-05-21 23:11 UTC, dKusakin requested changes

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        assertTrue(responseMail.getStatusCode() == 200, "Ожидаемый статус код 200");
`assertEquals` ?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        assertTrue(message.stream().filter(m -> m.getSubject().equalsIgnoreCase(topicDate)).count() == 1, "Письма с такой темой нет");
А концептуально тебе тут `anyMatch` не подойдет?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        assertTrue(message.stream().filter(m -> m.getSubject().equalsIgnoreCase(topicDate)).count() == 1, "Письма с такой темой нет");
И тут тоже

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +    private static String ckey;
Зачем его здесь хранить и тянуть постоянно в методы?
Это же характеристика заогиненного пользака через API, логично это в классе с API (у тебя это `MethodsForApi`) и хранить. Соответственно, после логина у тебя там поле будет инициализироваться, а после уже в методах юзаться

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +    private static Cookies cookiesAuto;
С куками, кстати, та же история, что и с `ckey`. Это же не данные для теста, они лишь вспомогательные, так что их то же логично вместе с API хранить, т.к. больше они тебе, скорее всего, нигде не потребуются

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +    void testSendMySelfEmail() {
По-моему, содержимое этого метода уж очень сильно похоже на содержимое предыдущего.
Надо бы что-то сделать с этой копипастой

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        cookiesAuto = auto.getAutorizationCookies();
По-моему, этот и два следующих логично было б скрыть в какой-нибудь общий метод `login`, ведь, по сути, все вместе они тебе только осуществляют вход. Вряд ли при создании ещё классов с тестами тебе захочется всё это копировать, а в случае изменений везде это изменять этот логин

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +    void testSendEmail() {
Кстати, давай для улучшения понимания того, что я тут написываю, выделим тесты с отправкой письма в отдельный класс, дабы сразу прочувствовать масштабируемость

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        String json = methods.getJsonStringForRequest(ckey, "1");
Не очень понятен смысл этого метода. Он же ходит всегда вместе с `getMessageList`? Если да, то почему бы его не сделать приватным и не инкапсулировать в целевой? К тому же, у него останется всего один аргумент - ид папки

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        methods.getSendMessegeAnswer(cookiesAuto, ckey, letterNew);
getSendMess**a**geAnswer

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +            if (state.equals("auth_challenge")) {
Оператор `&&`?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +        Response response2 = getLoginResponse(cookiesStart, token);
Что-то такое название переменных с индексом крайне слабо о чем-то говорит. Почему, например, не `loginResponse`?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +        System.out.println(response3);
Отладка?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +                        .post("https://passport.yandex.ru/registration-validations/auth/challenge/commit");
Можно урлу задавать кусочками, а общую часть (хост, общий участок пути) вынести в константу класса.
После вызова `given()` можно задать основную часть через `baseUri()`, ещё продолжение через `basePath()`.
Так ты как минимум избавишься от дубликатов

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +        assertTrue(response.getStatusCode() == 200);
С сообщением об ошибке, всё же, понятнее анализ проводить)
Да и можно было б через сам рест это сделать после `post()`:
```
.then()
.statusCode(200)
.extract().response();
```

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +                        .contentType("application/x-www-form-urlencoded")
Константа `ContentType.URLENC`?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/JsonRequestMessageClass.java
> +        JsonRequestMessageClass jsonClass = new JsonRequestMessageClass();
Так, метод, вроде как, не статический, поэтому я предполагал, что ты будешь взаимодействовать с имеющимся объектом, а ты создаешь новый. Получается, что изначальный объект не особо-то нужен?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/JsonRequestMessageClass.java
> +    private class Model {
Вот эти два внутренних логично сделать статическими, они ведь с конкретным объектом внешнего класса не связаны

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +        Response responseMail =
Точно эта переменная нужна? Там и дальше подобные вопросы есть, идея тебе тоже их задает.

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +                        .post("https://mail.yandex.ru/web-api/models/liza1?_m=messages");
По поводу урлы, её разбиения и вынесения части в константы написал в соседнем классе

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    @Step("мой вспомогательный метод чтение json из файла локально, потом убрать")
Про убрать уже говорили)

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +        assertTrue(responseSendMessage.getStatusCode() == 200,
`assertEquals` ? Следующий тоже

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/modelMessage/Data.java
> +    public ArrayList<MessageModels> message;
А зачем ограничивать именно `ArrayList` ? Мб я захочу использовать с `LinkedList` в качестве хранения

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/modelMessage/MessageModels.java
> +public class MessageModels {
Почему именно `MessageModels`, а не просто `Message` ?

2022-05-21 23:11 UTC, dKusakin commented on src/test/java/utils/apiUtils/modelMessage/Root.java
> +public class Root {
Добавить бы, что это не просто "корень", а "корень сообщений"

2022-05-22 19:08 UTC, YuliaTen commented on src/test/java/apiTest/YandexApiTest.java
> +    void testSendEmail() {
резко против разделения на два класса которые не завися друг от друга. Так как яндекс и так пропускает проверки один раз, потом говорит что я робот и блокирует на нное время, но смысл прибрать дубликаты и куки в методы уловила

2022-05-25 20:30 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        assertEquals(responseMail.getStatusCode(), 200, "Ожидаемый статус код 200");
Посмотри повнимательнее на порядок параметров в методе и это не только здесь, но и во всём проекте.
И да, статус-код можно и рестом было б проверить, но это не принципиально

2022-05-25 20:30 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +        assertEquals(message.stream().anyMatch(m -> m.getSubject().equalsIgnoreCase(topicDate)), true, "Письма с такой темой нет");
А тут почему от `assertTrue` отказалась?

2022-05-25 20:30 UTC, dKusakin commented on src/test/java/apiTest/YandexApiTest.java
> +    void testSendMySelfEmail() {
Всё ещё надо

2022-05-25 20:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    public List<Message> sendLetter(String reciver,String folderNum, String topicDate){
Какой-то сомнительный метод в целом.
Во-первых, хардкодишь какие-то макросы (зачем? Формируй в тесте объект письма и используй соответствующий метод для отправки)
Во-вторых, он занимается как отправкой писем, так и получением содержимого папки (зачем?). Нечто подобное можно было б сформировать в классе теста, но здесь это максимально странно

2022-05-25 20:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/JsonRequestMessageClass.java
> +        JsonRequestMessageClass jsonClass = new JsonRequestMessageClass();
Ещё актуально

2022-05-25 20:40 UTC, dKusakin commented on src/test/java/utils/apiUtils/modelMessage/Data.java
> +    public ArrayList<MessageModels> message;
Up

2022-05-25 21:30 UTC, dKusakin requested changes
- неправильное использование метода `assertEquals`
- невозможность потенциального логина разными пользователями
- дубликаты
- местами прибитые данные
- некорректное разделение обязанностей между классами
- не все предыдущие комментарии отработаны

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    private static TestData testData = new TestData();
Вот этой штукой ты прибила креды гвоздями. Что делать, если будет 2 пользователя? Например, от одного письмо отправляем другому и проверяем, дошло ли второму?

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    private DBConnect dbConnect = new DBConnect();
Очень нужен?

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    private Letters letter = dbConnect.getDataLetter();
А объект письма прибивать зачем? Это ж тестовые данные, они должны формироваться в тесте. Мы же хотим пользоваться классом с апи как околоуниверсальной штукой

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    private static AutorizationYandexApi auto = new AutorizationYandexApi();
Вот этим ты пользуешься ровно один раз при логине. Есть ли смысл его постоянно хранить?

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    private static Cookies cookiesAuto;
Не очень приветствую статику у кук и ключа (опять же, 2 пользователя. Вряд ли им это понравится)

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    public Response getMailAnswer(Cookies cookies) {
У тебя ж куки уже есть полем

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +        for (Element headline : newsHeadlines) {
Так мб сразу последний дернуть?

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    public String getDataFromResponseHTML(Response response, String attribute, String valueAttribute) {
Не очень уверен в месте хранения этого метода тут, но мб имеет смысл его сделать статиком, т.к. он не работает с состоянием, а использовать ты его явно не только тут планируешь

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +    private TestData testData = new TestData();
Опять гвозди

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +    private MethodsForApi methods = new MethodsForApi();
Хм, чую приближение кольца) В `MethodsForApi` у тебя есть поле с текущим классом, сомнительно

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +        String token = methods.getDataFromResponseHTML(response, "name", "csrf_token");
А, так он чисто ради этого метода. Точно надо что-то с этим делать

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +                        .formParam(" answer", "344093")
И снова хардкод

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +    private Cookies getControlAnswer(Cookies cookies, String track_id, String token) {
Чую, должен будет появиться четвертый параметр, а это уже явно перебор.
Я бы предложил куки и токен тут сделать полями

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +                        .formParam("login", testData.getLoginMail())
Почти хардкод. Логичнее было иметь логин через параметры метода

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/AutorizationYandexApi.java
> +                        .formParam("password", testData.getPasswordMail())
Аналогично логину

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    public String getTopicDate(){
Вряд ли этому методу место в классе по работе с API

2022-05-25 21:30 UTC, dKusakin commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +public class MethodsForApi {
Методы для АПИ? Любого?
Будь проще - ТындексПочтаАпи)

2022-05-31 21:33 UTC, YuliaTen commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    public Response getMailAnswer(Cookies cookies) {
уже убрала в тест класс

2022-06-01 07:57 UTC, YuliaTen commented on src/test/java/utils/apiUtils/MethodsForApi.java
> +    private static Cookies cookiesAuto;
статик убрала, а вот ключ оставила, пользователю в любом случае нужно залогинится, другому тоже, если он не залогинился( у меня это в before all ) то у него не будет возможности провести манипуляции с почтой, а если залогинен то ключ он получит свой при авторизации

2022-06-01 20:44 UTC, dKusakin requested changes
- допрятать работу с куками
- разобраться с разными `assert`
- прибрать лишние зависимости в pom'ах

2022-06-01 20:44 UTC, dKusakin commented on moduleApi/pom.xml
> +            <artifactId>json-simple</artifactId>
Ты его где-нибудь используешь?
Приберись немного в зависимостях модулей и общем тоже

2022-06-01 20:44 UTC, dKusakin commented on moduleApi/src/main/java/apiUtils/MethodsForYandexMailApi.java
> +    public Response loginMail(Cookies cookiesAuto){
Логиниться по кукам как-то странно.
Можно было б сюда пользователя передавать, а внутри метода создать объект того класса авторизации, через который получить куки и сохранить их в поле, т.к. таскать их аргументом тоже не очень

2022-06-01 20:44 UTC, dKusakin commented on moduleApi/src/main/java/apiUtils/MethodsForYandexMailApi.java
> +        Assert.assertEquals("Ожидаемый статус код 200, пришел - " + responseSendMessage.getStatusCode(),
Хм, а почему тут у `assertEquals` сначала сообщение, а потом значения?
В [тесте](https://github.com/YuliaTen/YandexTestSelenid/blob/developYulia/moduleApi/src/test/java/apiTest/YandexApiTest.java#L47) же наоборот

2022-06-01 20:44 UTC, dKusakin commented on moduleApi/src/test/java/apiTest/YandexApiTest.java
> +    private static Cookies cookiesAuto;
Не особо вижу смысла глядеть в тесте на куки. Работу с ними логичнее сныкать

2022-06-01 20:44 UTC, dKusakin commented on moduleApi/src/test/java/apiTest/YandexApiTest.java
> +    private DBConnect dbConnect = new DBConnect();
Так и осталась переменная ради одного её единственного вызова. Зачем?

2022-06-01 20:44 UTC, dKusakin commented on moduleApi/src/test/java/apiTest/YandexApiTest.java
> +    void methodSend(String reciver) {
Метод с названием "метод" :)
По названию шага я б предположил `sendLetter`

2022-06-01 20:44 UTC, dKusakin commented on moduleUtils/pom.xml
> +    <properties>
Вот этих всех `properties` достаточно в корневом pom.xml
Оттуда в дочерних подтянутся

2022-06-01 20:44 UTC, dKusakin commented on moduleUtils/pom.xml
> +            <artifactId>rest-assured</artifactId>
В утильном используется? Про остальные я б тоже подумал. Да и про плагин аллюра, тестов-то тут нет для него

2022-06-01 20:44 UTC, dKusakin commented on PREREQUISITES.md
> +[ER-диаграмма](.\moduleUtils\src\main\resources\modelER.png)
Хранить эту штуку в `src` явно не очень, так она всегда будет помещаться выходную папку, а потом и в jar.
Можно какую-нибудь папку в корне репозитория сделать и туда складывать

2022-06-02 07:13 UTC, YuliaTen commented on moduleApi/src/main/java/apiUtils/MethodsForYandexMailApi.java
> +        Assert.assertEquals("Ожидаемый статус код 200, пришел - " + responseSendMessage.getStatusCode(),
а это другой ассерт, он подсказал что в начала сообщение

2022-06-02 07:59 UTC, YuliaTen commented on moduleApi/src/main/java/apiUtils/MethodsForYandexMailApi.java
> +        Assert.assertEquals("Ожидаемый статус код 200, пришел - " + responseSendMessage.getStatusCode(),
изменила на Assertions

2022-06-02 08:00 UTC, YuliaTen commented on moduleUtils/pom.xml
> +            <artifactId>rest-assured</artifactId>
у меня используются Степы в тестдата

2022-06-02 20:16 UTC, dKusakin commented on moduleUtils/pom.xml
> +            <artifactId>rest-assured</artifactId>
За сами стэпы не плагин отвечает, а я только про него говорил :)

2022-06-02 21:49 UTC, YuliaTen commented on moduleUtils/pom.xml
> +            <artifactId>rest-assured</artifactId>
закинула

2022-06-03 12:27 UTC, dKusakin approved these changes

2022-06-03 12:29 UTC, merged